/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProduitsIndexRouteImport } from './routes/produits/index'
import { Route as CompteIndexRouteImport } from './routes/compte/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProduitsSlugRouteImport } from './routes/produits/$slug'
import { Route as CompteProfilRouteImport } from './routes/compte/profil'
import { Route as CompteMotDePasseOublieRouteImport } from './routes/compte/mot-de-passe-oublie'
import { Route as CompteInscriptionRouteImport } from './routes/compte/inscription'
import { Route as CompteConnexionRouteImport } from './routes/compte/connexion'
import { Route as CheckoutConfirmationRouteImport } from './routes/checkout/confirmation'
import { Route as AdminProduitsRouteImport } from './routes/admin/produits'
import { Route as AdminCommandesRouteImport } from './routes/admin/commandes'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminAvisRouteImport } from './routes/admin/avis'

const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsIndexRoute = ProduitsIndexRouteImport.update({
  id: '/produits/',
  path: '/produits/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteIndexRoute = CompteIndexRouteImport.update({
  id: '/compte/',
  path: '/compte/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsSlugRoute = ProduitsSlugRouteImport.update({
  id: '/produits/$slug',
  path: '/produits/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteProfilRoute = CompteProfilRouteImport.update({
  id: '/compte/profil',
  path: '/compte/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteMotDePasseOublieRoute = CompteMotDePasseOublieRouteImport.update({
  id: '/compte/mot-de-passe-oublie',
  path: '/compte/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteInscriptionRoute = CompteInscriptionRouteImport.update({
  id: '/compte/inscription',
  path: '/compte/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteConnexionRoute = CompteConnexionRouteImport.update({
  id: '/compte/connexion',
  path: '/compte/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutConfirmationRoute = CheckoutConfirmationRouteImport.update({
  id: '/checkout/confirmation',
  path: '/checkout/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProduitsRoute = AdminProduitsRouteImport.update({
  id: '/admin/produits',
  path: '/admin/produits',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommandesRoute = AdminCommandesRouteImport.update({
  id: '/admin/commandes',
  path: '/admin/commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAvisRoute = AdminAvisRouteImport.update({
  id: '/admin/avis',
  path: '/admin/avis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/panier': typeof PanierRoute
  '/admin/avis': typeof AdminAvisRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/produits': typeof AdminProduitsRoute
  '/checkout/confirmation': typeof CheckoutConfirmationRoute
  '/compte/connexion': typeof CompteConnexionRoute
  '/compte/inscription': typeof CompteInscriptionRoute
  '/compte/mot-de-passe-oublie': typeof CompteMotDePasseOublieRoute
  '/compte/profil': typeof CompteProfilRoute
  '/produits/$slug': typeof ProduitsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/compte/': typeof CompteIndexRoute
  '/produits/': typeof ProduitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/panier': typeof PanierRoute
  '/admin/avis': typeof AdminAvisRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/produits': typeof AdminProduitsRoute
  '/checkout/confirmation': typeof CheckoutConfirmationRoute
  '/compte/connexion': typeof CompteConnexionRoute
  '/compte/inscription': typeof CompteInscriptionRoute
  '/compte/mot-de-passe-oublie': typeof CompteMotDePasseOublieRoute
  '/compte/profil': typeof CompteProfilRoute
  '/produits/$slug': typeof ProduitsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/compte': typeof CompteIndexRoute
  '/produits': typeof ProduitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/panier': typeof PanierRoute
  '/admin/avis': typeof AdminAvisRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/produits': typeof AdminProduitsRoute
  '/checkout/confirmation': typeof CheckoutConfirmationRoute
  '/compte/connexion': typeof CompteConnexionRoute
  '/compte/inscription': typeof CompteInscriptionRoute
  '/compte/mot-de-passe-oublie': typeof CompteMotDePasseOublieRoute
  '/compte/profil': typeof CompteProfilRoute
  '/produits/$slug': typeof ProduitsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/compte/': typeof CompteIndexRoute
  '/produits/': typeof ProduitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/panier'
    | '/admin/avis'
    | '/admin/categories'
    | '/admin/commandes'
    | '/admin/produits'
    | '/checkout/confirmation'
    | '/compte/connexion'
    | '/compte/inscription'
    | '/compte/mot-de-passe-oublie'
    | '/compte/profil'
    | '/produits/$slug'
    | '/admin/'
    | '/checkout/'
    | '/compte/'
    | '/produits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/panier'
    | '/admin/avis'
    | '/admin/categories'
    | '/admin/commandes'
    | '/admin/produits'
    | '/checkout/confirmation'
    | '/compte/connexion'
    | '/compte/inscription'
    | '/compte/mot-de-passe-oublie'
    | '/compte/profil'
    | '/produits/$slug'
    | '/admin'
    | '/checkout'
    | '/compte'
    | '/produits'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/contact'
    | '/panier'
    | '/admin/avis'
    | '/admin/categories'
    | '/admin/commandes'
    | '/admin/produits'
    | '/checkout/confirmation'
    | '/compte/connexion'
    | '/compte/inscription'
    | '/compte/mot-de-passe-oublie'
    | '/compte/profil'
    | '/produits/$slug'
    | '/admin/'
    | '/checkout/'
    | '/compte/'
    | '/produits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ContactRoute: typeof ContactRoute
  PanierRoute: typeof PanierRoute
  AdminAvisRoute: typeof AdminAvisRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCommandesRoute: typeof AdminCommandesRoute
  AdminProduitsRoute: typeof AdminProduitsRoute
  CheckoutConfirmationRoute: typeof CheckoutConfirmationRoute
  CompteConnexionRoute: typeof CompteConnexionRoute
  CompteInscriptionRoute: typeof CompteInscriptionRoute
  CompteMotDePasseOublieRoute: typeof CompteMotDePasseOublieRoute
  CompteProfilRoute: typeof CompteProfilRoute
  ProduitsSlugRoute: typeof ProduitsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  CompteIndexRoute: typeof CompteIndexRoute
  ProduitsIndexRoute: typeof ProduitsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits/': {
      id: '/produits/'
      path: '/produits'
      fullPath: '/produits/'
      preLoaderRoute: typeof ProduitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte/': {
      id: '/compte/'
      path: '/compte'
      fullPath: '/compte/'
      preLoaderRoute: typeof CompteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits/$slug': {
      id: '/produits/$slug'
      path: '/produits/$slug'
      fullPath: '/produits/$slug'
      preLoaderRoute: typeof ProduitsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte/profil': {
      id: '/compte/profil'
      path: '/compte/profil'
      fullPath: '/compte/profil'
      preLoaderRoute: typeof CompteProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte/mot-de-passe-oublie': {
      id: '/compte/mot-de-passe-oublie'
      path: '/compte/mot-de-passe-oublie'
      fullPath: '/compte/mot-de-passe-oublie'
      preLoaderRoute: typeof CompteMotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte/inscription': {
      id: '/compte/inscription'
      path: '/compte/inscription'
      fullPath: '/compte/inscription'
      preLoaderRoute: typeof CompteInscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte/connexion': {
      id: '/compte/connexion'
      path: '/compte/connexion'
      fullPath: '/compte/connexion'
      preLoaderRoute: typeof CompteConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/confirmation': {
      id: '/checkout/confirmation'
      path: '/checkout/confirmation'
      fullPath: '/checkout/confirmation'
      preLoaderRoute: typeof CheckoutConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produits': {
      id: '/admin/produits'
      path: '/admin/produits'
      fullPath: '/admin/produits'
      preLoaderRoute: typeof AdminProduitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/commandes': {
      id: '/admin/commandes'
      path: '/admin/commandes'
      fullPath: '/admin/commandes'
      preLoaderRoute: typeof AdminCommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/avis': {
      id: '/admin/avis'
      path: '/admin/avis'
      fullPath: '/admin/avis'
      preLoaderRoute: typeof AdminAvisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ContactRoute: ContactRoute,
  PanierRoute: PanierRoute,
  AdminAvisRoute: AdminAvisRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCommandesRoute: AdminCommandesRoute,
  AdminProduitsRoute: AdminProduitsRoute,
  CheckoutConfirmationRoute: CheckoutConfirmationRoute,
  CompteConnexionRoute: CompteConnexionRoute,
  CompteInscriptionRoute: CompteInscriptionRoute,
  CompteMotDePasseOublieRoute: CompteMotDePasseOublieRoute,
  CompteProfilRoute: CompteProfilRoute,
  ProduitsSlugRoute: ProduitsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  CompteIndexRoute: CompteIndexRoute,
  ProduitsIndexRoute: ProduitsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
