export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

// NOTE: this file is normally auto-generated by Lovable Cloud by introspecting
// the live database. Since the catalog/orders/reviews migration
// (supabase/migrations/20261001000000_catalog_orders_reviews.sql) hasn't been
// applied to the live project from this environment, the Tables below are
// hand-written to match that migration exactly, purely so local type-checking
// works. Once the migration is applied, Lovable will regenerate this file —
// it should come back matching what's below; if it doesn't, the migration and
// this file have drifted and the real generated one wins.
export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.18"
  }
  public: {
    Tables: {
      categories: {
        Row: { slug: string; label: string; sort_order: number; created_at: string; updated_at: string }
        Insert: { slug: string; label: string; sort_order: number; created_at?: string; updated_at?: string }
        Update: { slug?: string; label?: string; sort_order?: number; created_at?: string; updated_at?: string }
        Relationships: []
      }
      subcategories: {
        Row: {
          category_slug: string
          slug: string
          label: string
          sort_order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          category_slug: string
          slug: string
          label: string
          sort_order: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          category_slug?: string
          slug?: string
          label?: string
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "subcategories_category_slug_fkey"
            columns: ["category_slug"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["slug"]
          },
        ]
      }
      products: {
        Row: {
          id: string
          name: string
          alt: string
          image: string
          images: Json
          category_slug: string
          subcategory_slug: string | null
          original_price: number
          discount_percent: number
          rating: number
          popularity: number
          is_new: boolean
          created_at: string
          stock_quantity: number
          featured: boolean
          sku: string | null
          weight_kg: number | null
          dimensions: Json | null
          description: string | null
          updated_at: string
        }
        Insert: {
          id: string
          name: string
          alt: string
          image: string
          images?: Json
          category_slug: string
          subcategory_slug?: string | null
          original_price: number
          discount_percent?: number
          rating?: number
          popularity?: number
          is_new?: boolean
          created_at?: string
          stock_quantity?: number
          featured?: boolean
          sku?: string | null
          weight_kg?: number | null
          dimensions?: Json | null
          description?: string | null
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          alt?: string
          image?: string
          images?: Json
          category_slug?: string
          subcategory_slug?: string | null
          original_price?: number
          discount_percent?: number
          rating?: number
          popularity?: number
          is_new?: boolean
          created_at?: string
          stock_quantity?: number
          featured?: boolean
          sku?: string | null
          weight_kg?: number | null
          dimensions?: Json | null
          description?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "products_category_slug_fkey"
            columns: ["category_slug"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["slug"]
          },
          {
            foreignKeyName: "products_category_slug_subcategory_slug_fkey"
            columns: ["category_slug", "subcategory_slug"]
            isOneToOne: false
            referencedRelation: "subcategories"
            referencedColumns: ["category_slug", "slug"]
          },
        ]
      }
      orders: {
        Row: {
          order_number: string
          created_at: string
          status: "nouvelle" | "en_traitement" | "expédiée" | "terminée"
          items: Json
          subtotal: number
          discount_total: number
          delivery_fee: number
          total: number
          customer_name: string
          phone: string
          email: string
          address: string
          city: string
          region: string
          delivery_method: "pickup" | "delivery"
          delivery_slot: string | null
          payment_method: "cod" | "wave" | "bank-transfer"
        }
        Insert: {
          order_number: string
          created_at?: string
          status?: "nouvelle" | "en_traitement" | "expédiée" | "terminée"
          items: Json
          subtotal: number
          discount_total?: number
          delivery_fee?: number
          total: number
          customer_name: string
          phone: string
          email: string
          address: string
          city: string
          region: string
          delivery_method: "pickup" | "delivery"
          delivery_slot?: string | null
          payment_method: "cod" | "wave" | "bank-transfer"
        }
        Update: {
          order_number?: string
          created_at?: string
          status?: "nouvelle" | "en_traitement" | "expédiée" | "terminée"
          items?: Json
          subtotal?: number
          discount_total?: number
          delivery_fee?: number
          total?: number
          customer_name?: string
          phone?: string
          email?: string
          address?: string
          city?: string
          region?: string
          delivery_method?: "pickup" | "delivery"
          delivery_slot?: string | null
          payment_method?: "cod" | "wave" | "bank-transfer"
        }
        Relationships: []
      }
      reviews: {
        Row: {
          id: string
          product_id: string
          name: string
          rating: number
          comment: string
          date: string
          approved: boolean
        }
        Insert: {
          id?: string
          product_id: string
          name: string
          rating: number
          comment: string
          date?: string
          approved?: boolean
        }
        Update: {
          id?: string
          product_id?: string
          name?: string
          rating?: number
          comment?: string
          date?: string
          approved?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "reviews_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
